on:
  push:
    branches:
      - master

jobs:
  export_game:
    # Always use ubuntu-latest for this action
    runs-on: ubuntu-latest
    name: Export game to Github
    steps:
      - name: checkout
        uses: actions/checkout@v4
        # Ensure that you get the entire project history
        with:
          fetch-depth: 0

      - name: create game release
        uses: firebelley/godot-export@v5.2.0
        id: export
        with:
          godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/4.3/beta1/Godot_v4.3-beta1_linux.x86_64.zip
          godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/4.3/beta1/Godot_v4.3-beta1_export_templates.tpz
          relative_project_path: .
          archive_output: true
        env:
          GITHUB_TOKEN: ${{ secrets.GH_CREDENTIALS }}
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

      - name: create release
        uses: ncipollo/release-action@v1.12.0
        with:
          token: ${{ secrets.GH_CREDENTIALS }}
          generateReleaseNotes: true
          tag: ${{ github.ref_name }}
          artifacts: ${{ steps.export.outputs.archive_directory }}/*
